### ISSUE TITLE
GCP marketplace integration has automated tests against the latest GKE versions

### ISSUE THREAD

**Issue by izgeri** [cyberark/conjur-google-cloud-marketplace#26]
Given that tooling changes with K8s versions, and GKE stays pretty up-to-date with the latest k8s versions, we should have automation that tests against the latest GKE versions so that we can be alerted to potential problems with our integration early.

**Comment by diverdane** [comment]
This will be handled by:
1) Re-creating the `onboarding-cluster` GKE cluster that we use for CI testing
    using "Regular" release channel. Reference: https://cloud.google.com/kubernetes-engine/docs/concepts/release-channels#channels
    This has been done on 3/10/2020.
2) Adding a chronological trigger to the Conjur Google Cloud marketplace repo.
    This will be done as part of this pull: https://github.com/cyberark/conjur-google-cloud-marketplace/pull/27

**Comment by diverdane** [comment]
This is being closed because it has been addressed and daily chron jobs are running on a GKE cluster that has regular updates to the Kubernetes version that is uses. There were 2 parts to this:

- Re-creating the onboarding-cluster GKE cluster that we use for CI testing using "Regular" release channel. Reference: https://cloud.google.com/kubernetes-engine/docs/concepts/release-channels#channels. This was done on 3/10/2020.
- Adding a chronological trigger to the Conjur Google Cloud marketplace repo.
This will be done as part of this pull: #27
